- args:
    sql: CREATE TABLE "public"."dcd_config"("key" text NOT NULL, "value" jsonb NOT
      NULL DEFAULT '{}', PRIMARY KEY ("key") );
  type: run_sql
- args:
    name: dcd_config
    schema: public
  type: add_existing_table_or_view
